### ISSUE TITLE
Update all local modules to the latest software version

### ISSUE THREAD

**Issue by LilyAnderssonLee** [nf-core/viralrecon#448]
### Description of feature

Please update all modules used in the pipeline to the latest version:
 - Update the modules in nf-core/modules
 - Add the latest modules to the pipeline

**Comment by saramonzon** [comment]
Let's keep this issue for updating pipeline modules that are NOT in nf-core modules

**Comment by svarona** [comment]
- [x] asciigenome.nf #476 
- [ ] kraken2_build.nf #474 
- [x] multiqc_nanopore.nf #411 
- [x] rename_fasta_header.nf (Ubuntu 20.04 -> Ubuntu 24.04 & sed=4.7 -> sed=4.8)
- [x] collapse_primers.nf (python:3.9--1 -> python:3.13)
- [ ] make_bed_mask.nf #482 
- [x] plot_base_density.nf (MULLED: conda-forge::r-base=4.0.3 conda-forge::r-reshape2=1.4.4 conda-forge::r-optparse=1.6.6 conda-forge::r-ggplot2=3.3.3 conda-forge::r-scales=1.1.1 conda-forge::r-viridis=0.5.1 conda-forge::r-tidyverse=1.3.0 bioconda::bioconductor-biostrings=2.58.0 bioconda::bioconductor-complexheatmap=2.6.2)
  - NEW: conda-forge::r-base=4.4.3 conda-forge::r-reshape2=1.4.4 conda-forge::r-optparse=1.7.5 conda-forge::r-ggplot2=3.5.1 conda-forge::r-scales=1.3.0 conda-forge::r-viridis=0.6.5 conda-forge::r-tidyverse=2.0.0 bioconda::bioconductor-biostrings=2.74.0 bioconda::bioconductor-complexheatmap=2.22.0
- [ ] snpeff_ann.nf #475 
- [x] filter_blastn.nf (Ubuntu 20.04 -> Ubuntu 24.04 & sed=4.7 -> sed=4.8)
- [x] make_variants_long_table.nf (MULLED: conda-forge::python=3.9.5 conda-forge::matplotlib=3.5.1 conda-forge::pandas=1.3.5 conda-forge::r-sys=3.4 conda-forge::regex=2021.11.10 conda-forge::scipy=1.7.3)
  - NEW: conda-forge::python=3.13.2 conda-forge::matplotlib=3.10.1 conda-forge::pandas=2.2.3 conda-forge::r-sys=3.4.3 conda-forge::regex=2024.11.6 conda-forge::scipy=1.15.2
- [x] plot_mosdepth_regions.nf (MULLED: same plot_base_density.nf)
- [ ] snpeff_build.nf #475 
- [x] ivar_variants_to_vcf.nf (MULLED: conda-forge::python=3.9.5 conda-forge::matplotlib=3.5.1 conda-forge::pandas=1.3.5 conda-forge::r-sys=3.4 conda-forge::regex=2021.11.10 conda-forge::scipy=1.7.3 conda-forge::biopython=1.79)
  - NEW: conda-forge::python:3.13.2 conda-forge::matplotlib=3.10.1 conda-forge::pandas=2.2.3 conda-forge::r-sys=3.4.3 conda-forge::regex=2024.11.6 conda-forge::scipy=1.15.2 conda-forge::biopython=1.85
- [x] multiqc_illumina.nf #411 
- [x] prepare_primer_fasta.nf (Ubuntu 20.04 -> Ubuntu 24.04 & sed=4.7 -> sed=4.8)
- [ ] snpsift_extractfields.nf #475
